import customtkinter

janela = customtkinter.CTk()
janela.geometry("800x400")
janela.title("Sistema de Cadastro")
janela.resizable(width=False, height=False)
janela._set_appearance_mode("light")

frame1 = customtkinter.CTkFrame(janela,width=570,height=330).place(x=10,y=30)
frame2 = customtkinter.CTkFrame(janela,width=180,height=180).place(x=590,y=30)

labelnome = customtkinter.CTkLabel(janela,text="Nome: ")
labelnome.place(x=15,y=37)
labelendereco = customtkinter.CTkLabel(janela,text="Endereço: ")
labelendereco.place(x=15,y=72)
labelcidade = customtkinter.CTkLabel(janela,text="Cidade: ")
labelcidade.place(x=15,y=112)
labelcep = customtkinter.CTkLabel(janela,text="CEP: ")
labelcep.place(x=15,y=152)
labelestado = customtkinter.CTkLabel(janela,text="Estado: ")
labelestado.place(x=15,y=192)

textboxnome = customtkinter.CTkTextbox(janela,width=300,height=30,border_spacing=2)
textboxnome.place(x=78,y=35)
textboxnome.insert("0.0","Bruno César Vilela")
textboxendereco = customtkinter.CTkTextbox(janela,width=300,height=30,border_spacing=2)
textboxendereco.place(x=78,y=71)
textboxendereco.insert("0.0","Rua Antônio Justiniano dos Reis 311")
textboxcidade = customtkinter.CTkTextbox(janela,width=300,height=30,border_spacing=2)
textboxcidade.place(x=78,y=111)
textboxcidade.insert("0.0","Carmo da Cachoeira")
textboxcep = customtkinter.CTkTextbox(janela,width=300,height=30,border_spacing=2)
textboxcep.place(x=78,y=151)
textboxcep.insert("0.0","37225-000")
textboxestado = customtkinter.CTkTextbox(janela,width=300,height=30,border_spacing=2)
textboxestado.place(x=78,y=191)
textboxestado.insert("0.0","Minas Gerais")

botao1 = customtkinter.CTkButton(frame1, text="Novo", corner_radius=10, hover_color="green").place(x=615,y=40)

janela.mainloop()